-- Flyway migration: create table sample_entity (H2/PostgreSQL compatible)
CREATE TABLE IF NOT EXISTS sample_entity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP NOT NULL
);

-- Index to speed up common lookups by name
CREATE INDEX IF NOT EXISTS idx_sample_entity_name ON sample_entity(name);
